<div class="col-lg-<?php echo $span;?> col-md-<?php echo $span;?> col-sm-<?php echo ($cols > 2 && $cols % 2 == 0) ? $span * 2 : $span; ?> col-xs-<?php echo $mini;?> _item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?> product-col <?php if($layout_mode !='grid'){ echo "col-fullwidth";} ?> ">
<div class="wrap-item">
    <div class="product-block">
            <?php if(isset($is_related) && $is_related ): ?>
            <?php if(!$_product->isComposite() && $_product->isSaleable()): ?>
                    <?php if (!$_product->getRequiredOptions()): ?>
                        <input type="checkbox" class="checkbox related-checkbox" id="related-checkbox<?php echo $_product->getId() ?>" name="related_products[]" value="<?php echo $_product->getId() ?>" />
                    <?php endif; ?>
                <?php endif; ?>
            <?php endif; ?>
            <?php
                $swap_class = "";
                $productId = $_product->getId();
                if($swap_image && $hover_image = $helper->getProductImage($_product->getId(), $swap_image_number, $list_image_width, $list_image_height)) {
                        $swap_class = "swap";
                 } 
            ?>
                    <div class="image <?php echo $swap_class; ?>">
                        <?php  //Sale Icon ?>
                            <?php 
                            if($enable_sale_icon) {
                                // Get the Special Price
                                $_product2 = Mage::getModel('catalog/product')->load($productId);

                                $specialprice = $_product2->getSpecialPrice(); 
                                // Get the Special Price FROM date
                                $specialPriceFromDate = $_product2->getSpecialFromDate();
                                // Get the Special Price TO date
                                $specialPriceToDate = $_product2->getSpecialToDate();
                                // Get Current date
                                $today =  time();
                             
                                if ($specialprice) {
                                    if($today >= strtotime( $specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime( $specialPriceFromDate) && is_null($specialPriceToDate)) {
                            ?>
                                    <span class="onsale"><span><?php echo $this->__("Sale");?></span></span>
                            <?php  
                                    }
                                }
                            }
                            ?>
                            <?php // New icon ?>
                             <?php
                                if($enable_new_icon) {
                                    $is_new = Mage::helper("ves_tempcp")->checkProductIsNew( $_product );
                                    
                                    if($is_new) { ?>
                                    <span class="new-icon"><span><?php echo $this->__("New");?></span></span>
                                    <?php

                                    }
                                }
                            ?>
                           <div class="product-img img">
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image img">

                            <?php if(isset($enable_lazyload) && $enable_lazyload) { /* Enable lazyload*/ ?>

                            <img class="lazy" data-original="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($list_image_width,$list_image_height); ?>" width="<?php echo $list_image_width; ?>" height="<?php echo $list_image_height; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                            <noscript><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($list_image_width,$list_image_height); ?>" width="<?php echo $list_image_width; ?>" height="<?php echo $list_image_height; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></noscript>

                            <?php } else { ?>

                             <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($list_image_width,$list_image_height); ?>" width="<?php echo $list_image_width; ?>" height="<?php echo $list_image_height; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />

                            <?php } ?>
                            </a>
                            <?php if($swap_image && $hover_image = $helper->getProductImage($_product->getId(), $swap_image_number, $list_image_width, $list_image_height)) { ?>
                                    <span class="hover-image">
                                        <a class="img" href="<?php echo $_product->getProductUrl(); ?>">

                                            <?php if(isset($enable_lazyload) && $enable_lazyload) { /* Enable lazyload */?>

                                            <img class="lazy" data-original="<?php echo $hover_image; ?>" width="<?php echo $list_image_width; ?>" height="<?php echo $list_image_height; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
                                            <noscript><img src="<?php echo $hover_image; ?>" width="<?php echo $list_image_width; ?>" height="<?php echo $list_image_height; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"></noscript>

                                            <?php } else { ?>

                                            <img src="<?php echo $hover_image; ?>" width="<?php echo $list_image_width; ?>" height="<?php echo $list_image_height; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
                                            <?php } ?>

                                        </a>
                                    </span>
                            <?php } ?>

                            

                            <?php // Image Popup ?>
                            <?php if( $enable_pzoom ): ?>
                                <?php
                                    if(!isset($_product2)) {
                                        $_product2 = Mage::getModel('catalog/product')->load($productId);
                                    }
                                ?>
                                <a href="<?php echo $this->helper('catalog/image')->init($_product2, 'image')->resize($popup_image_width, $popup_image_height);?>" class="colorbox product-zoom" title="<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>"> <span> Zoom image </span> </a>
                            <?php endif; ?>
                            
                        </div>
                    </div>

                   

                    <?php if($layout_mode !='grid'): ?>
                    <?php endif; ?>
                    <?php // Product description ?>

                    <div class="product-meta product-shop">
                        <div class="left">
                            <?php if( $show_title ): ?>
                                <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                                <h3 class="product-name name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h3>
                            <?php endif; ?>

                            <?php echo $this->getReviewsSummaryHtml($_product, true, true)?>

                            <?php if($show_price): ?>
                                <div class="price" >
                                    <?php echo $this->getPriceHtml($_product, true, $price_prefix) ?>
                                </div>
                            <?php endif; ?>

                            <?php if($enable_short_desc): ?>
                                <div class="desc std">
                                    <?php
                                        $product_short_desc = $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description');
                                        echo Mage::helper("ves_tempcp")->subString($product_short_desc, $desc_maxchar, "");
                                    ?>
                                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                                </div>
                            <?php endif; ?>
                        </div>
                        <div class="right">
                            <div class="actions">
                            <?php if($_product->isSaleable()): ?>
                                <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="<?php if($ajax_cart) { ?>addToCart('<?php echo $this->getAddToCartUrl($_product) ?>')<?php } else { ?>setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')<?php } ?>"><span><span><i class="fa fa-shopping-cart"> </i> <?php echo $this->__('Add to Cart') ?></span></span></button>
                            <?php else: ?>
                                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                            <?php endif; ?>
                            <?php if($show_compare_wishlist) { ?>
                            <ul class="add-to-links">
                                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                    <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" data-toggle="tooltip" title="<?php echo $this->__("Wishlist");?>" class="link-wishlist"><i class="fa fa-heart"></i></a></li>
                                <?php endif; ?>
                                <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                    <li class="hidden-xs"><a href="<?php echo $_compareUrl ?>" data-toggle="tooltip" title="<?php echo $this->__("Compare");?>" class="link-compare"><i class="fa fa-retweet"></i></a></li>
                                <?php endif; ?>
                            </ul>
                            <?php } ?>
                        </div>                          
                        </div>                            
                    </div> 
                    <?php if ($quickview) { ?>
                        <a class="a-quickview ves-colorbox hidden-xs" href="<?php echo Mage::helper("ves_tempcp")->getQuickviewURL( $_product->getId() ); ?>">
                        <span class="fa fa-plus"></span>
                        <span><?php echo $this->__('Quick View'); ?> </span></a>
                    <?php } ?>       
            </div>
        </div>

</div>

    
