<?php
$moduleId = rand().time();
$cols =  (int)$this->getConfig( "columns" );
$cols = !empty($cols)?$cols:1;
$span = 12/$cols;
$itemsperpage = $cols;

$auto_play = $this->getConfig( "auto_play" );
if ($auto_play) {
	$auto_play = true;
}
$auto_play = false;
$interval  = $this->getConfig( "interval" );

$c = $this->getGeneralConfig( 'small_imagesize', "" );
$tmp = explode( "x", $c );


$thumb_width = $thumb_height = "";
if( count($tmp) > 0 && (int)$tmp[0] ){
	$thumb_width = (int)$tmp[0];
	$thumb_height = (int)$tmp[1];
}

?>
<div class="block productcarousel venus-latest-block" id="module<?php echo $moduleId; ?>">
	<?php if( $this->getConfig("latestmod_title") ) : ?>
		<div class="block-title">
			<strong> <span><?php echo $this->getConfig( "latestmod_title" ); ?> </span> </strong>
		</div>	
	<?php endif; ?>
	
	<div class="block-content">
		<div class="box-vesblog carousel slide" id="vesblogcarousel<?php echo $moduleId;?>">
			<?php if( count($posts) > $itemsperpage) { ?>
			<?php if( $this->getConfig("enable_blognavmodule") ){ ?>
			<div class="carousel-controls">
				<a class="carousel-control left fa fa-angle-left" href="#vesblogcarousel<?php echo $moduleId;?>" data-slide="prev"></a>
				<a class="carousel-control right fa fa-angle-right" href="#vesblogcarousel<?php echo $moduleId;?>" data-slide="next"></a>
			</div>
			<?php } ?>
			<?php } ?>
			<div class="carousel-inner no-margin">
				<?php if( $this->getConfig("latestmod_desc") ) :?>
					<div class="block-description">
						<p><?php echo $this->getConfig("latestmod_desc"); ?></p>
					</div>
				<?php endif; ?>
				<?php $i = 0;?>

				<?php foreach( $posts as $post ): $i++?>

					<?php if($i == 1 || ($i-1) % $cols == 0) { ?>
					<div class="item row clearfix <?php if(($i-1)==0) {?>active<?php } ?>">
						<?php } ?>
						<div class="col-lg-<?php echo $span;?> col-sm-<?php echo $span;?> col-xs-12 <?php if(($i-1) % $cols == 0){echo "first";}  if($i%$cols == 0){echo "last";} ?>"    >
							<div class="post-block">
								<?php
								$image = "";
								if($thumb_width && $thumb_height) {
									$image = Mage::helper('ves_blog')->resizeImage($post->getFile(), "custom-s", $thumb_width, $thumb_height);
								} else {
									$image = $post->getImageURL( "s" );
								}
								?>
								<div class="post-image"><a href="<?php echo $post->getURL();?>" title="<?php echo $post->getTitle();?>">
									<img src="<?php echo $image;?>" class="post-image" alt="<?php echo $post->getTitle();?>"/>
								</a>
							</div>
							<h4><a href="<?php echo $post->getURL();?>" title="<?php echo $post->getTitle();?>"><?php echo $post->getTitle(); ?></a></h4>
							<div class="latest-description"><?php echo $post->getDescription(); ?></div>

							<?php if( $this->getConfig("latest_show_commentcouter") || $this->getConfig("latest_showcreated") || $this->getConfig("latest_show_hits")) :?>
								<div class="blog-meta">

									<?php if($this->getConfig("latest_showcreated")) { ?>
									<div class="blog-updated">
										<span><?php echo $this->__("Last Update");?></span>
										<?php echo $post->getUpdated(); ?>
									</div>
									<?php } ?>

									<?php if($this->getConfig("latest_show_hits")) { ?>
									<div class="blog-hits"><span><?php echo $this->__("Read");?></span> <strong><?php echo $post->getHits(); ?></strong> <?php echo $this->__("Times"); ?></div>
									<?php } ?>

									<?php if($this->getConfig("latest_show_commentcouter")) { ?>
									<div class="blog-comment-count"><?php echo $this->getCountingComment($post->getId());?> <?php  echo $this->__("Comment");?></div>
									<?php } ?>

								</div>

							<?php endif; ?>
							<p class="blog-readmore">
								<a href="<?php echo $post->getURL();?>" title="<?php echo $post->getTitle();?>">
									<?php echo $this->__("Read more...");?>
								</a>
							</p>
						</div>		
					</div>
					<?php if( $i%$cols == 0 || $i==count($posts) ) { ?>
				</div>
				<?php } ?>
			<?php endforeach; ?>
		</div>
	</div>	
</div>
</div>
<script type="text/javascript">
	jQuery('#vesblogcarousel<?php echo $moduleId;?>').carousel({interval:<?php echo $interval ?>,auto:<?php echo $auto_play ?>,pause:'hover', cycle: true});
</script>