 <?php // List mode ?>
    <?php if($layout_mode!='grid'): ?>
        <div class="item1<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
            <?php
            if(isset($enable_deals) && $enable_deals){
                    // Get the Discount
                    $save_price = (float)$_product->getPrice() - (float)$_product->getSpecialPrice();
                    $save_price_currency = Mage::helper('core')->currency($save_price, true, false);
                    $discount = round(($save_price/$_product->getPrice())*100);
                    $discount_string = " ".$discount."%";
            }
            ?>

            <?php if(isset($is_related) && $is_related ): ?>
            <?php if(!$_product->isComposite() && $_product->isSaleable()): ?>
                    <?php if (!$_product->getRequiredOptions()): ?>
                        <input type="checkbox" class="checkbox related-checkbox" id="related-checkbox<?php echo $_product->getId() ?>" name="related_products[]" value="<?php echo $_product->getId() ?>" />
                    <?php endif; ?>
                <?php endif; ?>
            <?php endif; ?>
            <div class="product-block">
                <div class="row">
                    <?php // Product Image ?>
                    <div class="col-lg-4 col-sm-4 col-xs-12">
                        <?php
                            if(isset($enable_deals) && $enable_deals){
                            // Get the Discount
                            $save_price = (float)$_product->getPrice() - (float)$_product->getSpecialPrice();
                            $save_price_currency = Mage::helper('core')->currency($save_price, true, false);
                            $discount = round(($save_price/$_product->getPrice())*100);
                            $discount_string = " ".$discount."%";
                    }
                    ?>
                    <?php
                        $swap_class = "";
                        $productId = $_product->getId();
                        if($swap_image && $hover_image = $helper->getProductImage($_product->getId(), $swap_image_number, $list_image_width, $list_image_height)) {
                                $swap_class = "swap";
                         } 
                    ?>
                        

                        <div class="image <?php echo $swap_class; ?>">
                           <?php  //Sale Icon ?>
                            <?php 
                            if($enable_sale_icon) {
                                // Get the Special Price
                                $_product2 = Mage::getModel('catalog/product')->load($productId);

                                $specialprice = $_product2->getSpecialPrice(); 
                                // Get the Special Price FROM date
                                $specialPriceFromDate = $_product2->getSpecialFromDate();
                                // Get the Special Price TO date
                                $specialPriceToDate = $_product2->getSpecialToDate();
                                // Get Current date
                                $today =  time();
                             
                                if ($specialprice) {
                                    if($today >= strtotime( $specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime( $specialPriceFromDate) && is_null($specialPriceToDate)) {
                            ?>
                                    <span class="onsale"><span><?php echo $this->__("Sale").$discount_string;?></span></span>
                            <?php  
                                    }
                                }
                            }
                            ?>
                            
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">

                                <?php if(isset($enable_lazyload) && $enable_lazyload) { // Enable lazyload?>

                                <img class="lazy" data-original="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($list_image_width, $list_image_height); ?>" width="<?php echo $list_image_width; ?>" height="<?php echo $list_image_height; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                                <noscript><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($list_image_width, $list_image_height); ?>" width="<?php echo $list_image_width; ?>" height="<?php echo $list_image_height; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></noscript>

                                <?php } else { ?>

                                <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($list_image_width, $list_image_height); ?>" width="<?php echo $list_image_width; ?>" height="<?php echo $list_image_height; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />

                                <?php } ?>
                            </a>
                             <?php if($swap_class) { ?>
                                <span class="hover-image">
                                    <a class="img" href="<?php echo $_product->getProductUrl(); ?>">
                                        <?php if(isset($enable_lazyload) && $enable_lazyload) { // Enable lazyload?>
                                        <img class="lazy" data-original="<?php echo $hover_image; ?>" width="<?php echo $list_image_width; ?>" height="<?php echo $list_image_height; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
                                        <noscript><img src="<?php echo $hover_image; ?>" width="<?php echo $list_image_width; ?>" height="<?php echo $list_image_height; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"></noscript>

                                        <?php } else { ?>
                                        <img src="<?php echo $hover_image; ?>" width="<?php echo $list_image_width; ?>" height="<?php echo $list_image_height; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
                                        <?php } ?>
                                    </a>
                                </span>
                                <?php } ?>
                        </div>
                        
                        <?php if( $enable_pzoom ) { ?>
                        <?php
                            if(!isset($_product2)) {
                                $_product2 = Mage::getModel('catalog/product')->load($productId);
                            }
                            
                        ?>

                        <a href="<?php echo $this->helper('catalog/image')->init($_product2, 'image')->resize($popup_image_width, $popup_image_height);?>" class="colorbox product-zoom" rel="colorbox" title="<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>"><span class="icon-zoom-in"></span></a>
                        <?php } ?>
                    </div>
                    <?php // Product description ?>
                    <div class="col-lg-8 col-sm-8 col-xs-12">
                        <div class="product-meta product-shop">
                            <?php if( $show_title ): ?>
                                <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                            <?php endif; ?>

                            <?php if($show_price) { ?>
                            <div class="price">
                                <?php echo $this->getPriceHtml($_product, true, $price_prefix) ?>
                            </div>
                            <?php } ?>
                            <?php if($show_review) { ?>
                            <div class="rating">
                                <?php echo $this->getReviewsSummaryHtml($_product, true, true)?>
                            </div>
                            <?php } ?>
                            <div class="desc std">
                                <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                            </div>

                            <?php if(isset($enable_deals) && $enable_deals){ ?>
                                <div class="deal_detail">
                                        <ul>
                                            <li>
                                                <span><?php echo $this->__("Discount");?></span>
                                                <span class="deal_detail_num"><?php echo $discount;?>%</span>
                                            </li>
                                            <li>
                                                <span><?php echo $this->__("You save");?></span>
                                                <span class="deal_detail_num"><span class="price"><?php echo $save_price_currency; ?></span></span>
                                            </li>
                                            <li>
                                                <span><?php echo $this->__("Bought");?></span>
                                                <span class="deal_detail_num"><?php echo Mage::helper("ves_tempcp")->getBought($_product->getSku());?></span>
                                            </li>
                                        </ul>
                                </div>
                            <?php } ?>

                            <div class="actions">
                                <?php if($_product->isSaleable()): ?>
                                <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="<?php if($ajax_cart) { ?>addToCart('<?php echo $this->getAddToCartUrl($_product) ?>')<?php } else { ?>setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')<?php } ?>"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                <?php else: ?>
                                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                <?php endif; ?>
                                <?php if($show_compare_wishlist) { ?>
                                <ul class="add-to-links">
                                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                        <li class="wishlist">
                                            <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" data-toggle="tooltip" title="<?php echo $this->__("Wishlist");?>" class="link-wishlist"><i class="fa fa-heart"></i></a></li>
                                        </li>
                                    <?php endif; ?>
                                    <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                    <li class="compare hidden-xs">
                                        <a href="<?php echo $_compareUrl ?>" class="link-compare" data-toggle="tooltip" title="<?php echo $this->__("Compare");?>"><i class="fa fa-retweet"></i></a>
                                    </li>
                                    <?php endif; ?>
                                </ul>
                                <?php } ?>
                            </div>

                            <?php if(isset($enable_deals) && $enable_deals){ ?>
                            <?php 
                                $date1 = date('G:i:s', strtotime($_product->getSpecialToDate()));
                                if ($date1 == "0:00:00") {
                                    $targetDate = date('m/d/Y \2\3\:\5\9\:\0\0', strtotime($_product->getSpecialToDate()));
                                }else{
                                    $targetDate = date('m/d/Y G:i:s', strtotime($_product->getSpecialToDate()));
                                } 
                            ?>
                            <div class="productdeals">
                                <div class="item-detail">
                                        <div class="timer-explain">(<?php echo date('m/d/Y', strtotime($_product->getSpecialToDate())); ?>)</div>   
                                    </div>
                                <div id="item<?php echo $module; ?>countdown_<?php echo $_product->getId(); ?>" class="item-countdown"></div>
                                <script type="text/javascript">
                                (function($){
                                        $("#item<?php echo $module; ?>countdown_<?php echo $_product->getId(); ?>").lofCountDown({
                                            formatStyle:2,
                                            TargetDate:"<?php echo $targetDate; ?>",
                                            DisplayFormat:"<ul><li>%%D%% <div><?php echo $this->__('Day');?></div></li><li> %%H%% <div><?php echo $this->__('Hours');?></div></li><li> %%M%% <div><?php echo $this->__('Mins');?></div></li><li> %%S%% <div><?php echo $this->__('Secs');?></div></li></ul>",
                                            FinishMessage:"<?php echo $this->__('Expired');?>",
                                        });
                                    })(jQuery);
                                </script>
                            </div>
                            <?php }?>  
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
    <?php else: ?>

    <?php // Grid Mode ?>
        <div class="col-xs-12 col-lg-<?php echo $span;?> col-sm-<?php echo $small;?> col-<?php echo $mini;?> item1<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">

            <?php
            if(isset($enable_deals) && $enable_deals){
                    // Get the Discount
                    $save_price = (float)$_product->getPrice() - (float)$_product->getSpecialPrice();
                    $save_price_currency = Mage::helper('core')->currency($save_price, true, false);
                    $discount = round(($save_price/$_product->getPrice())*100);
                    $discount_string = " ".$discount."%";
            }
            ?>

            <?php if(isset($is_related) && $is_related ): ?>
            <?php if(!$_product->isComposite() && $_product->isSaleable()): ?>
                    <?php if (!$_product->getRequiredOptions()): ?>
                        <input type="checkbox" class="checkbox related-checkbox" id="related-checkbox<?php echo $_product->getId() ?>" name="related_products[]" value="<?php echo $_product->getId() ?>" />
                    <?php endif; ?>
                <?php endif; ?>
            <?php endif; ?>
                <div class="product-block">         
                    <div class="image">
                        <?php  //Sale Icon ?>
                            <?php 
                            if($enable_sale_icon) {
                                // Get the Special Price
                                $_product2 = Mage::getModel('catalog/product')->load($productId);

                                $specialprice = $_product2->getSpecialPrice(); 
                                // Get the Special Price FROM date
                                $specialPriceFromDate = $_product2->getSpecialFromDate();
                                // Get the Special Price TO date
                                $specialPriceToDate = $_product2->getSpecialToDate();
                                // Get Current date
                                $today =  time();
                             
                                if ($specialprice) {
                                    if($today >= strtotime( $specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime( $specialPriceFromDate) && is_null($specialPriceToDate)) {
                            ?>
                                    <span class="onsale"><span><?php echo $this->__("Sale").$discount_string;?></span></span>
                            <?php  
                                    }
                                }
                            }
                            ?>

                        <div class="product-img">
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">

                            <?php if(isset($enable_lazyload) && $enable_lazyload) { // Enable lazyload?>
                            <img class="lazy" data-original="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($list_image_width,$list_image_height); ?>" width="<?php echo $list_image_width; ?>" height="<?php echo $list_image_height; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                            <noscript><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($list_image_width,$list_image_height); ?>" width="<?php echo $list_image_width; ?>" height="<?php echo $list_image_height; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></noscript>

                            <?php } else { ?>
                             <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($list_image_width,$list_image_height); ?>" width="<?php echo $list_image_width; ?>" height="<?php echo $list_image_height; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                            <?php } ?>
                            </a>
                            <?php if($swap_image && $hover_image = $helper->getProductImage($_product->getId(), $swap_image_number, $list_image_width, $list_image_height)) { ?>
                                    <span class="hover-image">
                                        <a class="img" href="<?php echo $_product->getProductUrl(); ?>">
                                            <?php if(isset($enable_lazyload) && $enable_lazyload) { // Enable lazyload?>
                                            <img class="lazy" data-original="<?php echo $hover_image; ?>" width="<?php echo $list_image_width; ?>" height="<?php echo $list_image_height; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
                                            <noscript><img src="<?php echo $hover_image; ?>" width="<?php echo $list_image_width; ?>" height="<?php echo $list_image_height; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"></noscript>
                                            <?php } else { ?>
                                            <img src="<?php echo $hover_image; ?>" width="<?php echo $list_image_width; ?>" height="<?php echo $list_image_height; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
                                            <?php } ?>
                                            </a>
                                    </span>
                            <?php } ?>
                        </div>
                        <?php if( $enable_pzoom ) { ?>
                        <?php
                            if(!isset($_product2)) {
                                $_product2 = Mage::getModel('catalog/product')->load($productId);
                            }
                            
                        ?>

                        <a href="<?php echo $this->helper('catalog/image')->init($_product2, 'image')->resize($popup_image_width);?>" class="colorbox product-zoom" rel="colorbox" title="<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>"><span class="icon-zoom-in"></span></a>
                        <?php } ?>
                        <div class="actions">
                            <?php if($_product->isSaleable()): ?>
                                <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="<?php if($ajax_cart) { ?>addToCart('<?php echo $this->getAddToCartUrl($_product) ?>')<?php } else { ?>setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')<?php } ?>"><span><span><i class="fa fa-shopping-cart"> </i> <?php echo $this->__('Add to Cart') ?></span></span></button>
                            <?php else: ?>
                                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                            <?php endif; ?>
                            <?php if($show_compare_wishlist) { ?>
                            <ul class="add-to-links">
                                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                    <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" data-toggle="tooltip" title="<?php echo $this->__("Wishlist");?>" class="link-wishlist"><i class="fa fa-heart"></i></a></li>
                                <?php endif; ?>
                                <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                    <li class="hidden-xs"><a href="<?php echo $_compareUrl ?>" data-toggle="tooltip" title="<?php echo $this->__("Compare");?>" class="link-compare"><i class="fa fa-retweet"></i></a></li>
                                <?php endif; ?>
                            </ul>
                            <?php } ?>
                        </div>
                    </div>
                    
                    <?php if( $show_title ): ?>
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                    <?php endif; ?>

                    <?php if($show_review): ?>
                    <div class="rating">
                    <?php echo $this->getReviewsSummaryHtml($_product, true, true)?>
                    </div>
                    <?php endif; ?>
                    
                    <div class="price">
                        <?php echo $this->getPriceHtml($_product, true, $price_prefix) ?>
                    </div>

                    <?php if(isset($enable_deals) && $enable_deals){ ?>
                                <div class="deal_detail">
                                        <ul>
                                            <li>
                                                <span><?php echo $this->__("Discount");?></span>
                                                <span class="deal_detail_num"><?php echo $discount;?>%</span>
                                            </li>
                                            <li>
                                                <span><?php echo $this->__("You save");?></span>
                                                <span class="deal_detail_num"><span class="price"><?php echo $save_price_currency; ?></span></span>
                                            </li>
                                            <li>
                                                <span><?php echo $this->__("Bought");?></span>
                                                <span class="deal_detail_num"><?php echo Mage::helper("ves_tempcp")->getBought($_product->getSku());?></span>
                                            </li>
                                        </ul>
                                </div>
                            <?php } ?>

                    <?php if(isset($enable_deals) && $enable_deals){ ?>
                            <?php 
                                $date1 = date('G:i:s', strtotime($_product->getSpecialToDate()));
                                if ($date1 == "0:00:00") {
                                    $targetDate = date('m/d/Y \2\3\:\5\9\:\0\0', strtotime($_product->getSpecialToDate()));
                                }else{
                                    $targetDate = date('m/d/Y G:i:s', strtotime($_product->getSpecialToDate()));
                                } 
                            ?>
                            <div class="productdeals">
                                <div class="item-detail">
                                        <div class="timer-explain">(<?php echo date('m/d/Y', strtotime($_product->getSpecialToDate())); ?>)</div>   
                                    </div>
                                <div id="item<?php echo $module; ?>countdown_<?php echo $_product->getId(); ?>" class="item-countdown"></div>
                                <script type="text/javascript">
                                (function($){
                                        jQuery("#item<?php echo $module; ?>countdown_<?php echo $_product->getId(); ?>").lofCountDown({
                                            formatStyle:2,
                                            TargetDate:"<?php echo $targetDate; ?>",
                                            DisplayFormat:"<ul><li>%%D%% <div><?php echo $this->__('Day');?></div></li><li> %%H%% <div><?php echo $this->__('Hours');?></div></li><li> %%M%% <div><?php echo $this->__('Mins');?></div></li><li> %%S%% <div><?php echo $this->__('Secs');?></div></li></ul>",
                                            FinishMessage:"<?php echo $this->__('Expired');?>",
                                        });
                                    })(jQuery);
                                </script>
                            </div>
                            <?php }?>
                    
                    
                    <?php if ($quickview) { ?>
                        <a class="a-quickview ves-colorbox hidden-xs" href="<?php echo Mage::helper("ves_tempcp")->getQuickviewURL( $_product->getId() ); ?>"><span class='fa fa-plus'></span><?php echo $this->__('Quick View'); ?></a>
                    <?php } ?>
                </div>
    </div>
<?php endif; ?>