<?php 
  $widget = $this->getWidget();
  $show_name = isset($widget['show_name'])?$widget['show_name']: 1;
  $categories = isset($widget['categories'])?$widget['categories']: array();
  $categories = is_array($categories)?$categories:explode(",", $categories);
  
  if($categories) {
    $category_model = isset($widget['category_model'])?$widget['category_model']:null;
    $collection = null;
    if($category_model) {
      $collection = $category_model->getCollection();
      $collection->addAttributeToSelect('url_key')
              ->addAttributeToSelect('name')
              ->addAttributeToSelect('all_children')
              ->addAttributeToSelect('is_anchor')
              ->setOrder('position', Varien_Db_Select::SQL_ASC)
              ->joinUrlRewrite()
              ->addAttributeToFilter('is_active', 1)
              ->addIdFilter($categories)
              ->load();
      $categories = $collection;
    }
    
?>
<?php if( isset($widget['widget_name']) & $show_name){
?>
<div class="menu-title"><?php echo $widget['widget_name'];?></div>
<?php
}?>
<div class="widget-category-list">
  <div class="widget-inner">
      <ul>
      <?php foreach ($categories as $category_id) { ?>
      <?php $category = is_object($category_id)?$category_id:Mage::getModel('catalog/category')->load($category_id); ?>
      <li><a href="<?php echo $category->getUrl(); ?>"><span><?php echo $category->getName();?></span></a></li>
      <?php } ?>
      </ul>
  </div>
</div>
<?php } ?>